name: STAGING Deploy to Cloud Run

on:
  push:
    branches: [staging]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: staging-web
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Container
        run: |
          docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/nextjs-repo/$SERVICE_NAME:${{ github.sha }} .
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/nextjs-repo/$SERVICE_NAME:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image=us-central1-docker.pkg.dev/$PROJECT_ID/nextjs-repo/$SERVICE_NAME:${{ github.sha }} \
            --platform=managed \
            --region=$REGION \
            --service-account="ai-search-chronos@chronos-sandbox.iam.gserviceaccount.com"
